apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{K8S_NAME}}
  labels:
    app: {{K8S_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{K8S_NAME}}
  template:
    metadata:
      labels:
        app: {{K8S_NAME}}
    spec:
      containers:
        - name: {{K8S_NAME}}
          image: {{K8S_NAME}}:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
